server {
    listen 80;
    server_name tweaky.skidz.ncsc;

    location / {
        proxy_pass http://fastapi:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

server {
    listen 80;
    server_name redacted.skidz.ncsc;

    location / {
        allow {{FASTAPI_IP}};
        deny all;

        proxy_pass http://flag:1337;
    }

    error_page 403 401 = @fallback;

    location @fallback {
        proxy_pass http://fastapi:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
    
}